name: E2E Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: [main]

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: e2e-tests
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v5
        name: checkout the code
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        name: setup go
        with:
          go-version-file: "go.mod"
          go-version: "1.24.x"

      - name: setup the latest version of kind
        uses: helm/kind-action@v1

      - name: verify installation
        run: |
          kind version
          kubectl version
