name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: read
    env:
      SECRET: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v5
        name: checkout the code
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        name: setup go
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Echo the secrets
        run: echo "${{ env.SECRET }}"
